### PR TITLE
Show Rubocop offense documentation without format

### LINKED ISSUE #397: Linter shows formatted offense documentation
## Describe the bug
The Rubocop offense documentation contains characters that are formatted as markdown text.

## Expected behavior
Show offense documentation without format.

```
The annotation keyword is followed by a colon and a space, then a note describing the problem.

# bad
def bar
  # FIXME This has crashed occasionally since v3.2.1.
  baz(:quux)
end

# good
def bar
  # FIXME: This has crashed occasionally since v3.2.1.
  baz(:quux)
end
```
## Actual behavior

```
The annotation keyword is followed by a colon and a space, then a note describing the problem.

[source,ruby]
----
# bad
def bar
  # FIXME This has crashed occasionally since v3.2.1.
  baz(:quux)
end

# good
def bar
  # FIXME: This has crashed occasionally since v3.2.1.
  baz(:quux)
end
----
```
## To Reproduce
Expand the documentation arrow in the linter message.

## Environment
 Please complete the following information:

 - All OS
 - Atom version 1.44
 - linter-rubocop 2.5.6
 - Ruby version manager: all
 - Rubocop version: 0.78

 ```
$ [bundle exec] rubocop -V
0.78.0 (using Parser 2.6.2.1, running on ruby 2.3.1 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by vzamanillo**
Fixes #397

### CODE REVIEW

File: src/rubocop/helpers/doc-cache.js [hunk 1]
```diff
@@ -20,6 +20,10 @@ function takeWhile(source, predicate) {
   return result
 }
 
+function formatDoc(text) {
+  return `<pre>${text.replace(/\[source,ruby\]|----/gi, '')}</pre>`
```
Comment (Arcanemagus) [inline src/rubocop/helpers/doc-cache.js]: Just a note that this isn't Markdown, although I'm not sure what markup language it is 🤷‍♂.

Comment (vzamanillo) [reply src/rubocop/helpers/doc-cache.js]: Yep, it is not markdown at all, I don't know what is it too, but the ruby comments with `# `are formatted as markdown.
